version: '2'
services:
    rwithjhipster-app:
        image: rwithjhipster
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://rwithjhipster-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=RwithJhipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rwithjhipster-mongodb:
        extends:
            file: mongodb.yml
            service: rwithjhipster-mongodb
